
name: Cypress Tests
on:
  push:
    branches: [ main, feature/*]
  pull_request:
    branches: [ main, release/develop ]
  workflow_dispatch:
    inputs:
      ambiente:
        description: 'Inserir o ambiente a ser executado os testes: dev / qa'
        required: false
        default: 'qa'
      browser:
        description: 'Selecionar algum destes browsers: chrome / electron  a ser executado os testes'
        type: choice
        options:
          - chrome
          - electron
          - firefox
        required: true
jobs:
  Execution_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run cy:test
